// <auto-generated />
namespace MVC_HighCar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adicionado_ordem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionado_ordem));
        
        string IMigrationMetadata.Id
        {
            get { return "201704120152150_adicionado_ordem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
